# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Automation_Project\GPON_auto_update\auto_update\AT_UD.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 40, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 120, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(340, 510, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 350, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setObjectName("label_3")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(170, 200, 241, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 200, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.MAC_DUT = QtWidgets.QListWidget(self.centralwidget)
        self.MAC_DUT.setGeometry(QtCore.QRect(170, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MAC_DUT.setFont(font)
        self.MAC_DUT.setObjectName("MAC_DUT")
        self.Cur_FW = QtWidgets.QListWidget(self.centralwidget)
        self.Cur_FW.setGeometry(QtCore.QRect(170, 80, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Cur_FW.setFont(font)
        self.Cur_FW.setObjectName("Cur_FW")
        self.new_FW = QtWidgets.QListWidget(self.centralwidget)
        self.new_FW.setGeometry(QtCore.QRect(170, 120, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.new_FW.setFont(font)
        self.new_FW.setObjectName("new_FW")
        self.update_times = QtWidgets.QListWidget(self.centralwidget)
        self.update_times.setGeometry(QtCore.QRect(170, 160, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update_times.setFont(font)
        self.update_times.setObjectName("update_times")
        self.Fw_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Fw_name_input.setGeometry(QtCore.QRect(200, 280, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Fw_name_input.setFont(font)
        self.Fw_name_input.setObjectName("Fw_name_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 290, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.FW_btn_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.FW_btn_confirm.setGeometry(QtCore.QRect(350, 280, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.FW_btn_confirm.setFont(font)
        self.FW_btn_confirm.setObjectName("FW_btn_confirm")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 520, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Harlow Solid Italic")
        font.setPointSize(11)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dialog_window = QtWidgets.QListWidget(self.centralwidget)
        self.dialog_window.setGeometry(QtCore.QRect(0, 390, 431, 111))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dialog_window.setFont(font)
        self.dialog_window.setObjectName("dialog_window")
        self.update_times_2 = QtWidgets.QListWidget(self.centralwidget)
        self.update_times_2.setGeometry(QtCore.QRect(170, 240, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update_times_2.setFont(font)
        self.update_times_2.setObjectName("update_times_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 240, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(450, 10, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Auto-Update-Firware"))
        self.label_1.setText(_translate("MainWindow", "MAC của DUT"))
        self.label_2.setText(_translate("MainWindow", "FW Hiện Tại"))
        self.label_5.setText(_translate("MainWindow", "FW Sẽ Update "))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "Thông Báo"))
        self.label_6.setText(_translate("MainWindow", "Tải FW vào DUT"))
        self.label_7.setText(_translate("MainWindow", "Số Lần Update"))
        self.Fw_name_input.setText(_translate("MainWindow", "GP5.03LP7.3.235"))
        self.label_8.setText(_translate("MainWindow", "Nhập tên bản FW update"))
        self.FW_btn_confirm.setText(_translate("MainWindow", "Xác nhận"))
        self.label_10.setText(_translate("MainWindow", "@Copy-right Raphael-RD-SwTeam"))
        self.label_9.setText(_translate("MainWindow", "Số Lần Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
