# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Automation_Project\GPON_auto_update\auto_update\AT_UD.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 657)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 310, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.MAC_DUT = QtWidgets.QListWidget(self.centralwidget)
        self.MAC_DUT.setGeometry(QtCore.QRect(130, 40, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MAC_DUT.setFont(font)
        self.MAC_DUT.setObjectName("MAC_DUT")
        self.Cur_FW = QtWidgets.QListWidget(self.centralwidget)
        self.Cur_FW.setGeometry(QtCore.QRect(130, 80, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Cur_FW.setFont(font)
        self.Cur_FW.setObjectName("Cur_FW")
        self.update_times = QtWidgets.QListWidget(self.centralwidget)
        self.update_times.setGeometry(QtCore.QRect(130, 120, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update_times.setFont(font)
        self.update_times.setObjectName("update_times")
        self.Fw_name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Fw_name_input.setGeometry(QtCore.QRect(130, 270, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Fw_name_input.setFont(font)
        self.Fw_name_input.setObjectName("Fw_name_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 260, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 610, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(16)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dialog_window = QtWidgets.QListWidget(self.centralwidget)
        self.dialog_window.setGeometry(QtCore.QRect(10, 340, 331, 201))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.dialog_window.setFont(font)
        self.dialog_window.setObjectName("dialog_window")
        self.connection_status = QtWidgets.QListWidget(self.centralwidget)
        self.connection_status.setGeometry(QtCore.QRect(130, 180, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.connection_status.setFont(font)
        self.connection_status.setObjectName("connection_status")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(10, 560, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.restart_btn.setGeometry(QtCore.QRect(250, 560, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.restart_btn.setFont(font)
        self.restart_btn.setObjectName("restart_btn")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.fw_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.fw_file_name.setGeometry(QtCore.QRect(130, 220, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fw_file_name.setFont(font)
        self.fw_file_name.setObjectName("fw_file_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Auto Upgrade Firware Tool by RDSWVN"))
        self.label_1.setText(_translate("MainWindow", "MAC của DUT"))
        self.label_2.setText(_translate("MainWindow", "FW Hiện Tại"))
        self.label_3.setText(_translate("MainWindow", "Thông Báo"))
        self.label_7.setText(_translate("MainWindow", "Số Lần Update"))
        self.Fw_name_input.setText(_translate("MainWindow", "Ví dụ : GP5.03MA7.3.235"))
        self.label_8.setText(_translate("MainWindow", "Nhập tên bản \n"
"FW upgrade"))
        self.label_10.setText(_translate("MainWindow", "@Copy-right Raphael VietNam RD-SW Team"))
        self.label_9.setText(_translate("MainWindow", "Trạng thái\n"
"kết nối với DUT"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.restart_btn.setText(_translate("MainWindow", "start"))
        self.label_11.setText(_translate("MainWindow", "Tên FIle"))
        self.fw_file_name.setText(_translate("MainWindow", "Ví dụ : tclinux_5.03MA.bin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
