# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Automation_Project\GPON_auto_update\auto_update\UI_module\AT_UD.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(419, 671)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 381, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: rgb(39, 39, 39);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(10, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(36, 36, 36);")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.MAC_DUT = QtWidgets.QListWidget(self.centralwidget)
        self.MAC_DUT.setGeometry(QtCore.QRect(180, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MAC_DUT.setFont(font)
        self.MAC_DUT.setObjectName("MAC_DUT")
        self.Cur_FW = QtWidgets.QListWidget(self.centralwidget)
        self.Cur_FW.setGeometry(QtCore.QRect(180, 90, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Cur_FW.setFont(font)
        self.Cur_FW.setObjectName("Cur_FW")
        self.update_times = QtWidgets.QListWidget(self.centralwidget)
        self.update_times.setGeometry(QtCore.QRect(180, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.update_times.setFont(font)
        self.update_times.setObjectName("update_times")
        self.Fw_target_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Fw_target_input.setGeometry(QtCore.QRect(180, 250, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Fw_target_input.setFont(font)
        self.Fw_target_input.setStyleSheet("color: rgb(145, 145, 0);")
        self.Fw_target_input.setObjectName("Fw_target_input")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 240, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 610, 261, 20))
        font = QtGui.QFont()
        font.setFamily("Freestyle Script")
        font.setPointSize(16)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.dialog_window = QtWidgets.QListWidget(self.centralwidget)
        self.dialog_window.setGeometry(QtCore.QRect(10, 320, 401, 231))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dialog_window.setFont(font)
        self.dialog_window.setAutoFillBackground(True)
        self.dialog_window.setStyleSheet("background-color: rgb(200, 200, 99);\n"
"")
        self.dialog_window.setProperty("isWrapping", False)
        self.dialog_window.setWordWrap(True)
        self.dialog_window.setObjectName("dialog_window")
        self.connection_status = QtWidgets.QListWidget(self.centralwidget)
        self.connection_status.setGeometry(QtCore.QRect(180, 170, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.connection_status.setFont(font)
        self.connection_status.setObjectName("connection_status")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(10, 560, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop_btn.setFont(font)
        self.stop_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(149, 0, 0);")
        self.stop_btn.setObjectName("stop_btn")
        self.restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.restart_btn.setGeometry(QtCore.QRect(310, 560, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.restart_btn.setFont(font)
        self.restart_btn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 66, 0);")
        self.restart_btn.setObjectName("restart_btn")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 210, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.fw_file_name = QtWidgets.QLineEdit(self.centralwidget)
        self.fw_file_name.setGeometry(QtCore.QRect(180, 210, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fw_file_name.setFont(font)
        self.fw_file_name.setStyleSheet("color: rgb(0, 191, 191);")
        self.fw_file_name.setObjectName("fw_file_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 419, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Auto Upgrade Firware Tool by RDSWVN"))
        self.label_1.setText(_translate("MainWindow", "MAC của DUT"))
        self.label_2.setText(_translate("MainWindow", "FW Hiện Tại"))
        self.label_3.setText(_translate("MainWindow", "Thông Báo"))
        self.label_7.setText(_translate("MainWindow", "Số Lần Update"))
        self.Fw_target_input.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:14pt;\">Nhập tên version fw vào đây.Ví dụ : GP5.03MA7.3.235</span></p></body></html>"))
        self.Fw_target_input.setText(_translate("MainWindow", "Ví dụ : GP5.03MA7.3.235"))
        self.label_8.setText(_translate("MainWindow", "Tên bản FW upgrade"))
        self.label_10.setText(_translate("MainWindow", "@Copy-right Raphael VietNam RD-SW Team"))
        self.label_9.setText(_translate("MainWindow", "Trạng thái\n"
"kết nối với DUT"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.restart_btn.setText(_translate("MainWindow", "Start"))
        self.label_11.setText(_translate("MainWindow", "Tên File"))
        self.fw_file_name.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Nhập tên file fw vào đây! Ví dụ : tclinux_5.03MA.bin</span></p></body></html>"))
        self.fw_file_name.setText(_translate("MainWindow", "Ví dụ : tclinux_5.03MA.bin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
